# PyTorch and Tensors

We can define tensors with different shapes. In general we have

| Rank | Math Entity | Python Example |
|------|-------------|----------------|
| 0    | Scalar      | `torch.tensor(1)` |
| 1    | Vector      | `torch.tensor([1, 2, 3])` |
| 2    | Matrix      | `torch.tensor([[1, 2], [3, 4]])` |
| 3    | 3-Tensor    | `torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])` |
| n    | n-Tensor    | `torch.randn(2, 3, 4, 5)` |

The following code will generate a simple tensor. 

In [13]:
import torch
import matplotlib.pyplot as plt
import numpy as np
scalar = torch.tensor(5)
print(scalar)  # tensor(5)
print(scalar.shape)  # torch.Size([])

tensor(5)
torch.Size([])


# 1D Tensors

A 1D tensor is basically a vector, we can produce one like this. 

In [7]:
vector = torch.tensor([1, 2, 3])
print(vector) 
print(vector.shape) 

tensor([1, 2, 3])
torch.Size([3])


## 2D Tensors

A 2d tensor is a matrix, we can produce one like this.

In [8]:
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(matrix)
# tensor([[1, 2, 3],
#         [4, 5, 6]])
print(matrix.shape)  # torch.Size([2, 3])

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


## 3 Tensor

This tensor has 3 dimensions, note how when printing the output is truncated.  

In [9]:
tensor3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(tensor3d)
print(tensor3d.shape)  

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
torch.Size([2, 2, 2])


## N Tensor

An N tensor is a tensor with N dimensions. These are typically created for existing data or functions as it is quite complex to generate higher order ones easily. 

In [10]:
tensor = torch.rand(2,3,4,5)
print(tensor)
print(tensor.shape)

tensor([[[[0.2427, 0.4552, 0.4872, 0.7850, 0.5079],
          [0.0618, 0.4205, 0.8676, 0.9544, 0.8629],
          [0.3455, 0.9419, 0.9714, 0.7753, 0.1489],
          [0.7451, 0.3483, 0.4283, 0.1448, 0.4689]],

         [[0.7161, 0.1850, 0.3478, 0.6003, 0.1614],
          [0.3213, 0.8152, 0.7646, 0.2333, 0.4037],
          [0.9694, 0.2593, 0.1044, 0.1079, 0.5982],
          [0.0035, 0.6947, 0.4354, 0.9020, 0.2718]],

         [[0.0353, 0.7808, 0.3296, 0.2135, 0.3135],
          [0.0178, 0.4738, 0.5902, 0.8079, 0.1110],
          [0.2938, 0.4709, 0.2908, 0.2135, 0.8880],
          [0.2065, 0.8248, 0.1540, 0.8519, 0.0066]]],


        [[[0.1294, 0.3065, 0.7871, 0.8884, 0.7127],
          [0.2749, 0.4011, 0.1187, 0.1497, 0.7466],
          [0.9658, 0.1696, 0.7159, 0.2847, 0.4593],
          [0.7343, 0.8411, 0.8159, 0.9385, 0.5838]],

         [[0.5666, 0.4600, 0.8450, 0.8331, 0.4919],
          [0.1534, 0.9571, 0.1984, 0.2035, 0.2634],
          [0.4726, 0.3310, 0.5302, 0.9580, 0.5476],
  

## Generating Tensors

There are a number of ways to generate tensors and pytorch comes with a number of functions to help us generate them.

### torch.tensor(data)

This method will generate a tensor from data passed in which could be a standard python container (list,tuple) or numpy array as follows.

In [22]:
from_tuple=torch.tensor(((1,2,3),(4,5,6)))
print(f"{from_tuple} {from_tuple.shape}")
from_list=torch.tensor([[1,2,3],[4,5,6]])
print(f"{from_list} {from_list.shape}")
data=np.random.rand(2,2,3)
from_array=torch.tensor(data)
print(f"{from_array} {from_array.shape}")

tensor([[1, 2, 3],
        [4, 5, 6]]) torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]]) torch.Size([2, 3])
tensor([[[0.4075, 0.8264, 0.3441],
         [0.4767, 0.6325, 0.7700]],

        [[0.3629, 0.5287, 0.8966],
         [0.2555, 0.9697, 0.4742]]], dtype=torch.float64) torch.Size([2, 2, 3])


## from similar values

As with numpy we can create arrays as zeros, ones of full values

In [36]:
tensor = torch.zeros(3, 3)
print(f"{tensor} {tensor.shape}")
tensor = torch.ones(3, 3)
print(f"{tensor} {tensor.shape}")
tensor = torch.full((3, 3), 7)
print(f"{tensor} {tensor.shape}")
tensor = torch.empty(2, 2) # uninitialized but most will set to zero
print(f"{tensor} {tensor.shape}")

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) torch.Size([3, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) torch.Size([3, 3])
tensor([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]]) torch.Size([3, 3])
tensor([[0., 0.],
        [0., 0.]]) torch.Size([2, 2])


## ranges

As with numpy there are a number of range based functions to generate tensors, most of them are of the format start,stop, step 

In [25]:
tensor = torch.arange(0, 10, 2)
print(f"{tensor} {tensor.shape}")
# Initializes a tensor with linearly spaced values between a start and end values
tensor = torch.linspace(0, 1, steps=5)
print(f"{tensor} {tensor.shape}")


tensor([0, 2, 4, 6, 8]) torch.Size([5])
tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000]) torch.Size([5])


## Identity and Diagonal

We can generate identity and diagonal matrices as follows, not there are other methods to set diagonals as well.

In [30]:
tensor=torch.eye(4)
print(f"{tensor} {tensor.shape}")
tensor=torch.diag(torch.tensor([1,2,3,4]))
print(f"{tensor} {tensor.shape}")
# We can set diagonals to a set value using 
tensor = torch.zeros(4, 4)

# Set all diagonal elements to 8
tensor.fill_diagonal_(8)
print(f"{tensor} {tensor.shape}")


tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]) torch.Size([4, 4])
tensor([[1, 0, 0, 0],
        [0, 2, 0, 0],
        [0, 0, 3, 0],
        [0, 0, 0, 4]]) torch.Size([4, 4])
tensor([[8., 0., 0., 0.],
        [0., 8., 0., 0.],
        [0., 0., 8., 0.],
        [0., 0., 0., 8.]]) torch.Size([4, 4])


## Random Tensors

We can generate random tensors as follows, note that the random number generation is based on the current random seed. The two core functions are the rand and randn functions which give us random values between 0 and 1 and random values from a normal distribution respectively.

We also have integer functions as well as random permutations, which can be useful for shuffling data.

In [33]:
tensor = torch.rand(3, 2)
print(f"{tensor} {tensor.shape}")
tensor = torch.randn(3, 2)
print(f"{tensor} {tensor.shape}")
# Random integers use low, high and size 
tensor = torch.randint(0, 10, (2, 3))
print(f"{tensor} {tensor.shape}")
# Initializes a tensor with a random permutation of integers from 0 to n-1.
tensor = torch.randperm(5)
print(f"{tensor} {tensor.shape}")


tensor([[0.1953, 0.5633],
        [0.6772, 0.2545],
        [0.0901, 0.2841]]) torch.Size([3, 2])
tensor([[-0.7728, -2.1594],
        [ 0.0672, -2.5894],
        [-2.7932,  0.5322]]) torch.Size([3, 2])
tensor([[9, 1, 4],
        [4, 9, 3]]) torch.Size([2, 3])
tensor([0, 3, 2, 4, 1]) torch.Size([5])


We can generate normal distributions based around a mean and standard deviation as follows.

In [42]:
tensor = torch.normal(mean=0, std=1, size=(2, 2))
print(f"{tensor} {tensor.shape}")

tensor([[-0.5969, -0.3649],
        [ 1.0527, -0.1846]]) torch.Size([2, 2])


There are more functions available in the documentation which can be found [here](https://pytorch.org/docs/stable/torch.html#creation-ops)

## Device

The following function will determine which device we have available. If we have properly installed PyTorch and setup for CUDA it should show ```cuda``` as the device. On mac you may get mps for the metal device (note not all things work with this), else we will get CPU, which is slower but should work fine. 

In [12]:
def get_device() -> torch.device:
    """
    Returns the appropriate device for the current environment.
    """
    if torch.cuda.is_available():
        return torch.device('cuda')
    elif torch.backends.mps.is_available(): # mac metal backend
        return torch.device('mps')
    else:
        return torch.device('cpu')

device = get_device()
print(device)  

mps
