# PyTorch and Tensors

We can define tensors with different shapes. In general we have

| Rank | Math Entity | Python Example |
|------|-------------|----------------|
| 0    | Scalar      | `torch.tensor(1)` |
| 1    | Vector      | `torch.tensor([1, 2, 3])` |
| 2    | Matrix      | `torch.tensor([[1, 2], [3, 4]])` |
| 3    | 3-Tensor    | `torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])` |
| n    | n-Tensor    | `torch.randn(2, 3, 4, 5)` |

The following code will generate a simple tensor. 

In [2]:
import torch
scalar = torch.tensor(5)
print(scalar)  # tensor(5)
print(scalar.shape)  # torch.Size([])

tensor(5)
torch.Size([])


# 1D Tensors

A 1D tensor is basically a vector, we can produce one like this. 

In [7]:
vector = torch.tensor([1, 2, 3])
print(vector) 
print(vector.shape) 

tensor([1, 2, 3])
torch.Size([3])


## 2D Tensors

A 2d tensor is a matrix, we can produce one like this.

In [8]:
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(matrix)
# tensor([[1, 2, 3],
#         [4, 5, 6]])
print(matrix.shape)  # torch.Size([2, 3])

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


## 3 Tensor

This tensor has 3 dimensions, note how when printing the output is truncated.  

In [9]:
tensor3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(tensor3d)
print(tensor3d.shape)  

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
torch.Size([2, 2, 2])


## N Tensor

An N tensor is a tensor with N dimensions. These are typically created for existing data or functions as it is quite complex to generate higher order ones easily. 

In [10]:
tensor = torch.rand(2,3,4,5)
print(tensor)
print(tensor.shape)

tensor([[[[0.2427, 0.4552, 0.4872, 0.7850, 0.5079],
          [0.0618, 0.4205, 0.8676, 0.9544, 0.8629],
          [0.3455, 0.9419, 0.9714, 0.7753, 0.1489],
          [0.7451, 0.3483, 0.4283, 0.1448, 0.4689]],

         [[0.7161, 0.1850, 0.3478, 0.6003, 0.1614],
          [0.3213, 0.8152, 0.7646, 0.2333, 0.4037],
          [0.9694, 0.2593, 0.1044, 0.1079, 0.5982],
          [0.0035, 0.6947, 0.4354, 0.9020, 0.2718]],

         [[0.0353, 0.7808, 0.3296, 0.2135, 0.3135],
          [0.0178, 0.4738, 0.5902, 0.8079, 0.1110],
          [0.2938, 0.4709, 0.2908, 0.2135, 0.8880],
          [0.2065, 0.8248, 0.1540, 0.8519, 0.0066]]],


        [[[0.1294, 0.3065, 0.7871, 0.8884, 0.7127],
          [0.2749, 0.4011, 0.1187, 0.1497, 0.7466],
          [0.9658, 0.1696, 0.7159, 0.2847, 0.4593],
          [0.7343, 0.8411, 0.8159, 0.9385, 0.5838]],

         [[0.5666, 0.4600, 0.8450, 0.8331, 0.4919],
          [0.1534, 0.9571, 0.1984, 0.2035, 0.2634],
          [0.4726, 0.3310, 0.5302, 0.9580, 0.5476],
  