# PyTorch and Tensors


| Rank | Math Entity | Python Example |
|------|-------------|----------------|
| 0    | Scalar      | `torch.tensor(1)` |
| 1    | Vector      | `torch.tensor([1, 2, 3])` |
| 2    | Matrix      | `torch.tensor([[1, 2], [3, 4]])` |
| 3    | 3-Tensor    | `torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])` |
| n    | n-Tensor    | `torch.randn(2, 3, 4, 5)` |


In [1]:
import torch
scalar = torch.tensor(5)
print(scalar)  # tensor(5)
print(scalar.shape)  # torch.Size([])

tensor(5)
torch.Size([])


# 1D Tensors

This will produce a vector

In [4]:
vector = torch.tensor([1, 2, 3])
print(vector)  # tensor([1, 2, 3])
print(vector.shape)  # torch.Size([3])

tensor([1, 2, 3])
torch.Size([3])


In [5]:
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(matrix)
# tensor([[1, 2, 3],
#         [4, 5, 6]])
print(matrix.shape)  # torch.Size([2, 3])

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


In [6]:
tensor3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(tensor3d)
# tensor([[[1, 2],
#          [3, 4]],
#         [[5, 6],
#          [7, 8]]])
print(tensor3d.shape)  # torch.Size([2, 2, 2])

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
torch.Size([2, 2, 2])
