# [Numpy](https://numpy.org/)

This notebook is a companion to the lecture slides [here](https://nccastaff.bournemouth.ac.uk/jmacey/SEForMedia/lectures/Lecture5/), it will be used to introduce numpy as well as other concepts. Note that we are still using Numpy 1.26.x so some of the newer features may not be available. For full documentation see [here](https://numpy.org/doc/1.26/index.html).

## Getting Started

numpy is already installed as part of the Anaconda distribution, so you should be able to import it directly. If you are using a different Python distribution you may need to install it using pip. The following code cell will import numpy and check the version you are using.

In [17]:
import numpy as np
print(np.__version__)

1.26.4


In the above example we import ```numpy as np``` this is a common convention as it makes it easier to type and read the code. We are creating an alias called ```np``` that contains all the numpy functions. This is a common convention in python programming. 

## Arrays

The core data type in numpy is the array, this is similar to a list but can be multi-dimensional. They can be created in a number of ways for example

1. Instantiated using values from a normal Python list
2. Filled with sequential values upto a target number
3. Filled with a specific value
4. Filled with random values (various random distributions [available](https://numpy.org/doc/1.26/reference/random/index.html)) 


For a full list of array creation routines, please see [here](https://numpy.org/doc/1.26/reference/routines.array-creation.html) 

In [18]:
#Array creation from python list
python_list = [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]
np_from_list = np.array(python_list)  
print(np_from_list, type(np_from_list))

[   2    4    8   16   32   64  128  256  512 1024] <class 'numpy.ndarray'>


In [19]:
# Array creation with sequential values 
# arange always returns a 1D array, will need to reshape it separately if
# we wish to do so
seq_array = np.arange(20)
print(seq_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [20]:
#Array creation with random values 
random_array = np.random.rand(10)  # returns an array filled with 10 random floats between 0 and 1
print(random_array)

[0.95866176 0.45522084 0.14147968 0.53712351 0.10480419 0.70953051
 0.27996643 0.76973677 0.44206809 0.21784236]


In [21]:
#Array filled with the same specific value
filled_array = np.full(10, 255)  # returns an array filled with 10 instances of 255
print(filled_array)

[255 255 255 255 255 255 255 255 255 255]


## Array Shape

In NumPy, an array’s shape refers to the dimensions of the array, specifying how many elements it contains along each axis. The shape of a NumPy array is represented as a tuple of integers, where each integer represents the size of the array along that dimension.

This is a key concept in numpy as it allows you to create multi-dimensional arrays. For example, a 2D array has a shape of (rows, columns) and a 3D array has a shape of (depth, rows, columns). We use this to represent our data when we input it into a neural network.

So far we have only created 1D arrayas, but we can create multi-dimensional arrays by passing in a tuple of values to the array function.

**1D Array (Vector):**
- Shape: (n,) where n is the number of elements.



In [22]:
arr = np.array([1, 2, 3])
print(arr.shape)  # Output: (3,)

(3,)


**2D Array (Matrix):**

- Shape: (n, m) where n is the number of rows and m is the number of columns.

In [23]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(arr.shape)  # Output: (3, 2)

(3, 2)


**3D Array:**
- Shape: (n, m, p) where n is the number of matrices, m is the number of rows, and p is the number of columns in each matrix.

In [24]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr.shape)  # Output: (2, 2, 2)

(2, 2, 2)


### Why Do We Need Array Shapes?

1.	Understanding Data Structure: Knowing the shape of an array tells you how the data is organized. For example, whether the data is a single vector, a 2D matrix, or a multi-dimensional dataset is important for operations like indexing, reshaping, or applying functions.
2.	Efficient Computation: Many mathematical operations in NumPy, like matrix multiplication, element-wise operations, or broadcasting, depend on the array’s shape. Mismatched shapes can cause errors, so understanding the shape helps ensure proper operation.

## Reshaping Arrays

Reshaping an array means changing the shape of the array without changing the data it contains. This is a common operation when working with neural networks as we often need to change the shape of the data to fit the input layer of the network.

One of the many things that set Numpy arrays apart from Python lists is their `reshape` method. This allows you to define the number of dimensions that the structure represented by the array has. For example, the array `np_from_list` that we have just defined is just a flat list of numbers at the present. `reshape` helps us represent it as a 2D data structure (a matrix). Keep in mind that the shape that you put into this method must agree with the number of elements in the array. In our example, the array has 10 elements, so acceptable shapes include:
* 5, 2
* 2, 5
* 1, 10
* 10, 1

In [25]:
matrix_5_2 = np_from_list.reshape(5,2)
print(matrix_5_2)
print(f"{matrix_5_2.shape=}")

[[   2    4]
 [   8   16]
 [  32   64]
 [ 128  256]
 [ 512 1024]]
matrix_5_2.shape=(5, 2)


In [26]:
matrix_2_10 = seq_array.reshape(2,10)
print(matrix_2_10)
print(f"matrix_2_10 shape: {matrix_2_10.shape}")

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
matrix_2_10 shape: (2, 10)


In [27]:
# You can also pass a desired shape into the array creation function to instantiate
# an array with a pre-defined shape
array_from_shape = np.full(matrix_5_2.shape, 32)
array_from_shape

array([[32, 32],
       [32, 32],
       [32, 32],
       [32, 32],
       [32, 32]])

## Exercises

The following cells have been set up to help you learn how to use numpy. The comments in the cells will ask you to complete a simple numpy task. Experiment with the code and see what happens.

### Task 1

In [28]:
# Create a Numpy array A that contains the integers from 0 - 31 (32 elements long)


<details>

<summary>Solution</summary>

```python
A = np.arange(32)
print(A)
```

</details>

### Task 2

In [29]:
# Create a Numpy array B that contains 12 random numbers between 0 and 1


<details>

<summary>Solution</summary>

```python
B = np.random.rand(12)
print(B)
```

</details>

## Task 3

In [30]:
# Turn A into a 2d matrix of shape (8, 4) - 8 rows, 4 columns


<details>

<summary>Solution</summary>

```python
A = A.reshape(8, 4)
print(A)
```

</details>

## Task 4

In [31]:
# Turn B into a 2d matrix of shape (4, 3)


<details>

<summary>Solution</summary>

```python
B = B.reshape(4, 3)
print(B)
```

</details>

## Array operations

Once you have created an array, there are various operations you may want to perform on them. We'll go through some of the most common ones in the next few cells.

### Binary operators

Similar to normal counting numbers, Numpy arrays can be used as arguments to binary arithmetic operators like ```*``` (multiplication), ```+``` (addition), ```-```(subtraction) and ```/```(division). However, these can only be applied to arrays under certain conditions:

1. The arrays have the same shape, OR
2. The operation is between an array and a scalar, OR
3. The operations is between 2 arrays of different shapes that can be "broadcast" together - more on this later

These operations are applied **element-wise** meaning each element in the array is combined with its corresponding element at the same position in the other array

In [35]:
# Addition with a scalar
arr = np.random.rand(32).reshape((8,4))
print(arr.shape)
print(arr)
scalar_add_array = 11 + arr 
print(scalar_add_array)

(8, 4)
[[0.78111802 0.1767563  0.74445903 0.82919246]
 [0.6947885  0.82564827 0.68789781 0.2396228 ]
 [0.61852323 0.87572465 0.82649908 0.63237389]
 [0.38061821 0.91600969 0.44028765 0.40020483]
 [0.97601709 0.56581641 0.85081161 0.31060986]
 [0.0726094  0.37008896 0.19185561 0.13086161]
 [0.5865231  0.12040909 0.87782809 0.58312088]
 [0.66303347 0.75484801 0.19506405 0.62725284]]
[[11.78111802 11.1767563  11.74445903 11.82919246]
 [11.6947885  11.82564827 11.68789781 11.2396228 ]
 [11.61852323 11.87572465 11.82649908 11.63237389]
 [11.38061821 11.91600969 11.44028765 11.40020483]
 [11.97601709 11.56581641 11.85081161 11.31060986]
 [11.0726094  11.37008896 11.19185561 11.13086161]
 [11.5865231  11.12040909 11.87782809 11.58312088]
 [11.66303347 11.75484801 11.19506405 11.62725284]]


In [38]:
# Subtraction with another array of same shape
A  = np.full(32, 5).reshape((8,4)) # 8x4 matrix with all elements as 5
sub_array = arr - A 
print(sub_array)

[[-4.21888198 -4.8232437  -4.25554097 -4.17080754]
 [-4.3052115  -4.17435173 -4.31210219 -4.7603772 ]
 [-4.38147677 -4.12427535 -4.17350092 -4.36762611]
 [-4.61938179 -4.08399031 -4.55971235 -4.59979517]
 [-4.02398291 -4.43418359 -4.14918839 -4.68939014]
 [-4.9273906  -4.62991104 -4.80814439 -4.86913839]
 [-4.4134769  -4.87959091 -4.12217191 -4.41687912]
 [-4.33696653 -4.24515199 -4.80493595 -4.37274716]]
